modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

mixinConfig = [
    "create_steel_encased.mixins.json"
]

[[mods]]
modId = "${mod_id}"
version = "0.1.0"
displayName = "CSE core"
authors = "Gotve"
description = '''Crucial core mod fto'''


[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"


[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
